### ISSUE TITLE
Error (ValueError) calling screen.draw.text() with color gradient and wrapped text

### ISSUE THREAD

**Issue by charlesej** [lordmauve/pgzero#165] opened 2019-01-09 17:37 UTC
In certain cases calling `screen.draw.text()` will cause an error. The following things need to be in place to see this issue.
- text needs to be wrapped
- text needs to contain certain characters
- gradient color needs to be used
- font size needs to be above a certain size

This code will fail with the following error.
```
def draw():
    screen.draw.text('a\ng',
        (0,0),
        fontsize=18,
        gcolor='blue')
```
```
  File "C:\Program Files\Python 3.5\lib\site-packages\pgzero\ptext.py", line 349, in getsurf
    (1.0 - m) * array[:, :, j] + m * gcolor[j]).astype(array.dtype)
ValueError: operands could not be broadcast together with shapes (13,) (7,14)
```

These calls to `screen.draw.text()` work without issue.
```
def draw():
    screen.draw.text('a\ng',
        (0,0),
        fontsize=18)  # no gradient color

    screen.draw.text('a\ng',
        (0,0),
        fontsize=17,  # smaller font size
        gcolor='blue')

    screen.draw.text('a\nb',  # 'b' instead of 'g'
        (0,0),
        fontsize=18,
        gcolor='blue')

    screen.draw.text('g\ng', # 'g' instead of 'a'
        (0,0),
        fontsize=18,
        gcolor='blue')
```

System details:
- os: windows 10
- python: 3.5.0
- pygame: 1.9.4
- pgzero: 1.2 (also reproduced on master branch at ef963beaa22db89cb011695e96587bb268cbec2a)
- numpy: 1.15.4

**Comment by lordmauve** [comment] 2019-05-06 17:41
Can reproduce. This may well be fixed in [upstream pygame-text](https://github.com/cosmologicon/pygame-text/) but because it usually breaks something to upgrade I have made a quick fix in our vendored copy, and added a test.

**Closed as completed by lordmauve** 2019-05-06 17:41 UTC
