### ISSUE TITLE
How to run it in Pycharm?

### ISSUE THREAD

**Issue by Simplifier** [lordmauve/pgzero#177] opened 2019-03-19 18:07 UTC
Is a command line the only way to run pgzero scripts? Can I run it through a regular IDE?

**Comment by XenonLab-Studio** [comment] 2019-03-27 18:03
@Simplifier I use Pycharm and start my projects without problems.

Pygame Zero is a wrapper for Pygame, so your projects start identically.

If you use Windows 10, remember to set the environment variable (Python 3.x installation, select the path option). To install pygame and pygame zero use the pycharm function or open the Windows terminal (CMD) as an administrator, otherwise pip install will not be able to install libraries.

If you use Pychar or any other editor, you need to import the "pgzrun" library, then at the end of your code add "pgzrun.go ()" here is an example:

```python
import pgzrun

alien = Actor('alien')
alien.pos = 100, 56

WIDTH = 500
HEIGHT = alien.height + 20

def draw():
    screen.clear()
    alien.draw()

pgzrun.go()
```
Now PyCharm recognizes the "pgzrun" library and you can directly start the project by going to the main menu in: run ---> run 'main', or you can press: SHIFT + F10, to start the project directly (always use the main module ).

I hope I was clear. A greeting.

**Comment by lordmauve** [comment] 2019-03-28 17:38
Also [Mu](https://codewith.mu/) has support for Pygame Zero although I guess if you're asking about PyCharm you're looking for a full IDE rather than a cut-down educational one.

**Comment by Simplifier** [comment] 2019-04-03 17:14
@XenonLab-Studio, thanks for this helpful example! I accidentally missed it [in the documentation](https://pygame-zero.readthedocs.io/en/stable/ide-mode.html). The only flaw is that Pycharm can't resolve references like Actor etc here =(

@lordmauve, thanks for the pretty interesting link! I like it supports Jupyter out of the box

**Comment by XenonLab-Studio** [comment] 2019-04-03 18:00
@Simplifier I use PyCharm under Linux, it works perfectly Pygame Zero. Just remember to insert the library and the run function call as I wrote you. Mu editor is nice but it's still experimental, alternatively the best thing is just IDLE believe me :)

Happy coding friend ;)

**Comment by Simplifier** [comment] 2019-04-03 19:05
@XenonLab-Studio, yes, it works (compiles and runs successfully). But it can't recognize, where did Actor, screen etc come from. It's pretty annoying, because autocomplete doesn't work

I guess, Pygame Zero uses some kind of "dynamic magic", that's why PyCharm can't resolve references statically
![screen](https://user-images.githubusercontent.com/3374612/55505650-3bb1d180-565c-11e9-8501-3e75b8955d01.png)

**Comment by XenonLab-Studio** [comment] 2019-04-03 19:36
@Simplifier Yes, you are perfectly right! I also have the same problem, on various editors and ide, so it's a pgzero limit. I have also tested with vscode, atom text editor, pycharm, idle. I have the same problem as you. I'm sorry but I didn't remember this problem. Perhaps the problem is pygame? pygame zero, and pygame, both use "screen" so can it be a conflict in the code autocompletion system?

**Comment by lordmauve** [comment] 2019-05-06 13:48
Linters complaining about undefined built-ins is #61. Linters know about some of the built-ins in Python and will complain when we magically add more.

I'm going to close this issue, as I think there is no issue with PyCharm here.

**Closed as completed by lordmauve** 2019-05-06 13:48 UTC

**Comment by Marcinosoft** [comment] 2020-12-11 21:55
Just add following two lines under "import pgzrun":
<pre><code>import sys
mod = sys.modules['__main__']
</code></pre>

Then prefix all unresolved references like Actor, music, screen, animate, sounds, keyboard, clock
by `mod.`
Here is working example:

<pre><code>import pgzrun
import sys
mod = sys.modules['__main__']

alien = mod.Actor('alien')
alien.pos = 100, 56

WIDTH = 500
HEIGHT = alien.height + 20

def draw():
    mod.screen.clear()
    alien.draw()

pgzrun.go()
</code></pre>

**Comment by ehartford** [comment] 2022-08-29 02:09
@Marcinosoft this works - but is there a way i can set mod to global so i don't have to type "mod." before everything?
